version: 2
updates:
  - package-ecosystem: uv
    directory: "/"
    schedule:
      interval: daily
      time: "08:00"
    open-pull-requests-limit: 10
    reviewers:
    - caiocampos
    assignees:
    - caiocampos
