name: Install & Lint

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.14"]
    steps:
    - uses: actions/checkout@v7
    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v8.3.2
      with:
        enable-cache: true
        cache-prefix: ${{ matrix.python-version }}
    - name: Pin python-version ${{ matrix.python-version }}
      run: uv python pin ${{ matrix.python-version }}
    - name: Sync dependencies
      run: uv sync
    - name: Lint
      run: uvx ruff check
